=== yannkiraly/mln-extension-for-rapidminer/resources/GeneralParameter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  
		   targetNamespace="http://xsd.configuration.modelling.operator.rapidminer.com/GeneralParameter" 
		   xmlns:tns="http://xsd.configuration.modelling.operator.rapidminer.com/GeneralParameter" 
		   elementFormDefault="qualified">

<xs:element name= "generalParameters">
<xs:complexType>
	<xs:sequence>
		<xs:element name="generalParameter" minOccurs="0" maxOccurs="unbounded">
			<xs:complexType>
				<xs:attribute name="key" type="xs:string" use="required"/>
				<xs:attribute name="value" type="xs:string" use="required"/>	
				<xs:attribute name="topic" type="xs:string" use="required"/>
				<xs:attribute name="description" type="xs:string" use="required"/>
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>
</xs:element>

</xs:schema>

=== yannkiraly/mln-extension-for-rapidminer/resources/com/rapidminer/resources/extension/GeneralParameters.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:generalParameters xmlns:tns="http://xsd.configuration.modelling.operator.rapidminer.com/GeneralParameter" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://xsd.configuration.modelling.operator.rapidminer.com/GeneralParameter ../../../../../src/GeneralParameter.xsd ">
  
  <tns:generalParameter key="Temporary File Folder" topic="General"
     value=""
     description="Folder for temporary files."/>
  
  <tns:generalParameter key="Alchemy Executable Folder" topic="Alchemy" 
      value=""
  	description="Folder containing the Alchemy executables."/>
  
  <tns:generalParameter key="Alchemy Inference Executable" topic="Alchemy"
      value="infer" description="Name of the Alchemy inference executable."/>
  
  <tns:generalParameter key="Alchemy Weight Learning Executable" topic="Alchemy"
      value="learnwts" description="Name of the Alchemy weight learning executable."/>
  
  <tns:generalParameter key="Rockit JAR Folder" topic="Rockit"
      value=""
      description="Folder containing the Rockit jar."/>
  
  <tns:generalParameter key="Rockit JAR" topic="Rockit"
      value="rockit.jar"
      description="Name of the Rockit jar."/>
  
  <tns:generalParameter key="Rockit Configuration File" topic="Tuffy"
      value="rockit.properties"
      description="Name of the Rockit configuration file."/>
  
  <tns:generalParameter key="Tuffy JAR Folder" topic="Tuffy"
      value=""
      description="Folder containing the Tuffy jar."/>
  
  <tns:generalParameter key="Tuffy JAR" topic="Tuffy"
      value="tuffy.jar"
      description="Name of the Tuffy jar."/>
  
  <tns:generalParameter key="Tuffy Configuration File" topic="Tuffy"
      value="tuffy.conf"
       description="Name of the Tuffy configuration file."/>

</tns:generalParameters>
