=== yannkiraly/mln-extension-for-rapidminer/resources/OptionalParameterSpecification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xsd.configuration.modelling.operator.rapidminer.com/OptionalParameterSpecification" xmlns:tns="http://xsd.configuration.modelling.operator.rapidminer.com/OptionalParameterSpecification" elementFormDefault="qualified">

<xs:element name="optionalParameters">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="optionalParameter" type="tns:optionalParameter" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:complexType name="optionalParameter">
	<xs:sequence>
		<xs:element name="mlnEngines"  minOccurs="1" maxOccurs="1">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="mlnEngine" minOccurs="1" maxOccurs="unbounded">
						<xs:complexType>
							<xs:attribute name="key" type="xs:string"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="categories" minOccurs="0" maxOccurs="1">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="category" minOccurs="0" maxOccurs="unbounded">
						<xs:complexType>
							<xs:attribute name ="label" type="xs:string"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="parameterConditions" minOccurs="0" maxOccurs="1">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="parameterCondition" minOccurs="0" maxOccurs="unbounded">
						<xs:complexType>
							<xs:attribute name="class" type="xs:string"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
	</xs:sequence>
	<xs:attribute name="key" type="xs:string" use="required"/>
	<xs:attribute name="description" type="xs:string" use="required"/>
	<xs:attribute name="flag" type="xs:string"/>
	<xs:attribute name="numberOfArguments" type="xs:int"  use="required"/>
	<xs:attribute name="inferenceArgument" type="xs:boolean" use="required"/>
	<xs:attribute name="learnArgument" type="xs:boolean" use="required"/>
	<xs:attribute name="expert" type="xs:boolean" use="required"/>
	<xs:attribute name="minInt" type="xs:int"/>
	<xs:attribute name="maxInt" type="xs:int"/>
	<xs:attribute name="defaultCategoryIndex" type="xs:int"/>
	<xs:attribute name="defaultInt" type="xs:int"/>
	<xs:attribute name="defaultBoolean" type="xs:boolean"/>
	<xs:attribute name="parameterType" use="required">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="INT"/>
				<xs:enumeration value="STRING"/>
				<xs:enumeration value="CATEGORY"/>
				<xs:enumeration value="LIST"/>
				<xs:enumeration value="BOOLEAN"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
</xs:complexType>
</xs:schema>

=== yannkiraly/mln-extension-for-rapidminer/resources/com/rapidminer/resources/extension/OptionalParameterSpecifications.xml
<?xml version="1.0" encoding="UTF-8" ?>

<tns:optionalParameters xmlns:tns="http://xsd.configuration.modelling.operator.rapidminer.com/OptionalParameterSpecification" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mln.com/OptionalParameterSpecification ../../../../../src/com/rapidminer/operator/modelling/configuration/xsd/OptionalParameterSpecification.xsd ">
  <tns:optionalParameter key="Maximum Iterations" expert="true" parameterType="INT" defaultInt="20" description="Maximum learning iterations." 
      flag="-dMaxIter" inferenceArgument="false" learnArgument="true" minInt="0" maxInt="10000" numberOfArguments="1">
    <tns:mlnEngines>
      <tns:mlnEngine key="Tuffy"/>
    </tns:mlnEngines>
  </tns:optionalParameter>
   <tns:optionalParameter key="Don't break hard rules" expert="true" parameterType="BOOLEAN" 
       description="Don't break hard rules." 
      flag="-dontBreak" inferenceArgument="true" learnArgument="true" defaultBoolean="false" numberOfArguments="0">
    <tns:mlnEngines>
      <tns:mlnEngine key="Tuffy"/>
    </tns:mlnEngines>
  </tns:optionalParameter>
  <tns:optionalParameter key="MLE Inference" expert="true" parameterType="BOOLEAN" 
       description="Run MLE inference." 
      flag="-mle" inferenceArgument="true" learnArgument="false" defaultBoolean="false" numberOfArguments="0">
    <tns:mlnEngines>
      <tns:mlnEngine key="Tuffy"/>
    </tns:mlnEngines>
  </tns:optionalParameter>
  <tns:optionalParameter key="Marginal Inference Type" expert="true" parameterType="CATEGORY" 
       description="Choose the marginal inference algorithm to use." 
      flag="" inferenceArgument="true" learnArgument="false" numberOfArguments="1" defaultCategoryIndex="1">
     <tns:mlnEngines>
      <tns:mlnEngine key="Alchemy"/>
    </tns:mlnEngines>
    <tns:categories>
 	  <tns:category label="Gibbs Sampling"/>
 	   <tns:category label="MC-SAT"/>
 	</tns:categories>
    <tns:parameterConditions>
        <tns:parameterCondition class="com.rapidminer.condition.mln.OnlyForMarginalInferenceCondition"/>
    </tns:parameterConditions>
  </tns:optionalParameter>
  <tns:optionalParameter key="Maximum Steps" expert="true" parameterType="INT" defaultInt="20" description="Maximum MCMC Sampling Steps." 
      flag="-maxSteps" inferenceArgument="true" learnArgument="true" minInt="0" maxInt="10000" numberOfArguments="1">
    <tns:mlnEngines>
      <tns:mlnEngine key="Alchemy"/>
    </tns:mlnEngines>
  </tns:optionalParameter>
  <tns:optionalParameter key="Maximum Seconds" expert="true" parameterType="INT" defaultInt="20" description="Maximum seconds to run." 
      flag="-maxSeconds" inferenceArgument="true" learnArgument="true" minInt="0" maxInt="10000" numberOfArguments="1">
    <tns:mlnEngines>
      <tns:mlnEngine key="Alchemy"/>
    </tns:mlnEngines>
  </tns:optionalParameter>
  <tns:optionalParameter key="Iterations" expert="true" parameterType="INT" defaultInt="50" description="Number of rounds." 
      flag="-iterations" inferenceArgument="true" learnArgument="true" minInt="0" maxInt="10000" numberOfArguments="1">
    <tns:mlnEngines>
      <tns:mlnEngine key="Rockit"/>
    </tns:mlnEngines>
  </tns:optionalParameter>
  <tns:optionalParameter key="Maximum memory use" expert="true" parameterType="INT" defaultInt="512" 
      description="Maximum amount of memory to use in MB" 
      flag="-Xmx" inferenceArgument="true" learnArgument="true" minInt="0" maxInt="10000" numberOfArguments="1">
    <tns:mlnEngines>
      <tns:mlnEngine key="Rockit"/>
      <tns:mlnEngine key="Tuffy"/>
    </tns:mlnEngines>
  </tns:optionalParameter>
    <tns:optionalParameter key="Verbosity" expert="true" parameterType="INT" defaultInt="0" 
      description="Verbosity level" 
      flag="-verbose" inferenceArgument="true" learnArgument="true" minInt="0" maxInt="3" numberOfArguments="1">
    <tns:mlnEngines>
      <tns:mlnEngine key="Tuffy"/>
    </tns:mlnEngines>
  </tns:optionalParameter>
    <tns:optionalParameter key="Maximum number of samples" expert="true" parameterType="INT" defaultInt="100" 
      description="Maximum number of samples for MC-SAT" 
      flag="-mcsatSamples" inferenceArgument="true" learnArgument="true" minInt="0" maxInt="10000" numberOfArguments="1">
    <tns:mlnEngines>
      <tns:mlnEngine key="Tuffy"/>
    </tns:mlnEngines>
  </tns:optionalParameter>
    <tns:optionalParameter key="Multiple databases" expert="true" parameterType="BOOLEAN" 
      description="Treat multiple databases as separate" 
      flag="-multipleDatabases" inferenceArgument="true" learnArgument="true" numberOfArguments="0">
    <tns:mlnEngines>
        <tns:mlnEngine key="Alchemy"/>
    </tns:mlnEngines>
  </tns:optionalParameter>
</tns:optionalParameters>
